[workspace]
name = "raster-benchmark"
authors = ["Krzysztof Dyba"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
rasterio = ">=1.3.7,<2"
rasterstats = ">=0.20.0,<0.22"
rioxarray = ">=0.18.0,<0.20"
pandas = ">=2.2.3,<3"
geopandas = ">=1,<2"
