---
title: "Raster Benchmark"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r message=FALSE}
library(ggplot2)
```

```{r collapse=TRUE}
cat(paste("R", getRversion(), "\n"))
cat(paste("sf", packageVersion("sf"), "\n"))
cat(paste("stars", packageVersion("stars"), "\n"))
cat(paste("terra", packageVersion("terra"), "\n"))
cat(paste("raster", packageVersion("raster"), "\n"))
cat(paste("exactextractr", packageVersion("exactextractr")))
```

```{r collapse=TRUE}
# check it manually
cat("Python 3.17.3", "\n")
cat("rasterio 1.4.3", "\n")
cat("rasterstats 0.20.0", "\n")
cat("rioxarray 0.19.0")
```

```{r collapse=TRUE}
# check it manually
cat("Julia 1.11.7", "\n")
cat("Rasters_jl 0.14.6")
```

```{r}
files = list.files("results", full.names = TRUE)
df = lapply(files, read.csv2)
df = do.call(rbind, lapply(files, read.csv2,
                           colClasses = c("factor", "factor", "numeric")))
```

## Extract values by points
**68 275 points**

```{r extract-points}
df_agg = df[df$task == "extract-points", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Downsample
**30 to 90 m**

```{r downsample}
df_agg = df[df$task == "downsample", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Calculate NDVI

```{r ndvi}
df_agg = df[df$task == "ndvi", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.4) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.4) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Load rasters

```{r load}
df_agg = df[df$task == "load", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Write multilayer
**10 layers with masks, LZW compression**

```{r write}
df_agg = df[df$task == "write", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Crop
**by rectangular extent**

```{r crop}
df_agg = df[df$task == "crop", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Zonal statistics
**mean values for 1 940 buffers**

```{r zonal}
df_agg = df[df$task == "zonal", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")
labels = as.character(df_agg$package)
names(labels) = labels
labels[1:2] = c("exactextractr\n(raster)", "exactextractr\n(terra)")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  scale_x_discrete(labels = labels) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

See also the benchmark from the `{exactextractr}` package: https://github.com/isciences/exactextractr#performance

```{r final-plot, include=FALSE}
df_agg = aggregate(time ~ task + package, df, median)

# language as a new variable
python = c("rasterio", "rasterstats", "rioxarray")
df_agg$lang = ifelse(df_agg$package %in% python, "Python", NA)
df_agg$lang = ifelse(df_agg$package %in% "rasters_jl", "Julia", df_agg$lang)
df_agg$lang[is.na(df_agg$lang)] = "R"
df_agg$lang = as.factor(df_agg$lang)

# capitalize task names
levels(df_agg$task) = tools::toTitleCase(levels(df_agg$task))
levels(df_agg$task)[3] = "Extract Points"
levels(df_agg$task)[5] = "NDVI"

# drop slower funs from same packages 
pkg_drop = c("raster-overlay", "stars-st_apply", "terra-fun", "exactextractr-raster")
df_agg = df_agg[!df_agg$package %in% pkg_drop, ]

# return only first part of string
pkg_name = strsplit(as.character(df_agg$package), "-")
df_agg$package = sapply(pkg_name, "[[", 1)

p = ggplot(df_agg, aes(x = package, y = time)) +
  geom_point(aes(shape = lang, color = package), size = 2) +
  facet_wrap(vars(task), scales = "free_y") +
  # override circles with diamonds in legend
  guides(colour = guide_legend(override.aes = list(shape = 18, size = 3.5))) +
  labs(title = "Benchmark raster operations",
       caption = "https://github.com/kadyb/raster-benchmark",
       color = "Package", shape = "Language") +
  scale_color_brewer(palette = "Set1") +
  ylab("Time [s]") +
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        plot.caption.position = "plot",
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(colour = "black")
        )
p
```

```{r}
ggsave("comparison.png", p, width = 800, height = 500, units = "px", scale = 2.5)
```

```{r}
timings = aggregate(time ~ task + package, df, median)
colnames(timings)[3] = "median"
timings$median = round(timings$median, 2)
write.csv(timings, "timings.csv", row.names = FALSE, quote = FALSE)
```
